(define (count-change amount) 
(define (cc amnt kinds-of-coins) (
    (cond ((= amnt 0) 1)
        ()
    )
))
(define (first-denomination kinds-of-coins)
    (cond ((= kinds-of-coins 1) 1)
        ((= kinds-of-coins 2) 5)
        ((= kinds-of-coins 3) 10)
        ((= kinds-of-coins 4) 25)
        ((= kinds-of-coins 5) 50)
    ))
(cc amount 5))
