(load "exercise.4.6.scm")

(define (eval expr env)
  (cond ((self-evaluating? expr) expr)
        ((variable? expr) (lookup-variable-value expr env))
        ((quoted? expr) (text-of-quotation expr))
        ((assignment? expr) (eval-assignment expr env))
        ((definition? expr) (eval-definition expr env))
        ((if? expr) (eval-if expr env))
        ((lambda? expr) (make-procedure (lambda-parameters expr)
                                        (lambda-body expr)
                                        env))
        ((let? expr) (eval (let->combination expr) env))
        ((let*? expr) (eval (let*->nested-lets expr) env))
        ((begin? expr)
         (eval-sequence (begin-actions expr) env))
        ((cond? expr) (eval (cond->if expr) env))
        ((application? expr)
         (apply (eval (operator expr) env)
                (list-of-values (operands expr) env)))
        (else
         (error "Unknown expression type: EVAL" expr))))

(define (let->combination expr)
  (cons (make-lambda (let-vars expr) (let-body expr))
        (let-exps expr)))
(define (let*? expr) (tagged-list? 'let* expr))

(define (let*->nested-lets expr)
  (if (<= 1 (length (let-pairs expr)))
      (let->combination expr)
      (list 'let (car (let-pairs expr)) ('let* (cdr (let-pairs expr)) (let-body expr)))))
