(define (make-account balance password)
  (let ((consecutive-failed 0))
    (define (call-the-cops x)
      (error "Hands up, you are under arrested, sir!" x))
    (define (withdraw amount)
      (if (>= balance amount)
          (begin (set! balance (- balance amount))
                 balance)
          "Insufficient funds"))
    (define (deposit amount)
      (set! balance (+ balance amount))
      balance)
    (define (dispatch pswd m)
      (if (not (eq? pswd password))
          (begin (set! consecutive-failed (+ consecutive-failed 1))
                 (if (>= consecutive-failed 3)
                     call-the-cops
                     (error "Incorrect password")))
          (begin (set! consecutive-failed 0)
                 (cond ((eq? m 'withdraw) withdraw)
                       ((eq? m 'deposit) deposit)
                       (else (error "Unknown request -- MAKE-ACCOUNT" m))))))
    dispatch))
