(define (make-monitored f)
  (let ((call-cnt 0))
    (define (reset-count) (set! call-cnt 0))
    (define (how-many-calls?) call-cnt)
    (define (dispatch x)
      (cond ((eq? x 'how-many-calls?) call-cnt)
            ((eq? x 'reset-count) (set! call-cnt 0))
            (else (begin (set! call-cnt (+ call-cnt 1)) (f x)))))
    dispatch))
