(define x (list 1 (list 2 (list 3 4) 5) (list 6 7)))
(define (square-root tree)
  (map (lambda (sub-tree)
         (if (pair? sub-tree)
             (square-root sub-tree)
           (* sub-tree sub-tree)))
       tree))
